/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgricultureTip {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'crop' : string,
}
export interface AgricultureTipInput {
  'title' : string,
  'content' : string,
  'crop' : string,
}
export interface ComputerService {
  'id' : bigint,
  'duration' : string,
  'name' : string,
  'description' : string,
  'price' : number,
}
export interface ComputerServiceInput {
  'duration' : string,
  'name' : string,
  'description' : string,
  'price' : number,
}
export type Department = { 'computer' : null } |
  { 'agriculture' : null };
export interface Enquiry {
  'id' : bigint,
  'customerName' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
  'department' : string,
}
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'category' : string,
  'department' : Department,
  'price' : number,
}
export interface ProductUpdateInput {
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'category' : string,
  'department' : Department,
  'price' : number,
}
export interface ServiceRequest {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'serviceType' : string,
  'description' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface _SERVICE {
  'addAgricultureTip' : ActorMethod<[AgricultureTipInput], bigint>,
  'addComputerService' : ActorMethod<[ComputerServiceInput], bigint>,
  'addProduct' : ActorMethod<[ProductUpdateInput], bigint>,
  'deleteAgricultureTip' : ActorMethod<[bigint], undefined>,
  'deleteComputerService' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllAgricultureTips' : ActorMethod<[], Array<AgricultureTip>>,
  'getAllComputerServices' : ActorMethod<[], Array<ComputerService>>,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getEnquiriesByDepartment' : ActorMethod<[string], Array<Enquiry>>,
  'getProductsByDepartment' : ActorMethod<[Department], Array<Product>>,
  'submitEnquiry' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'submitServiceRequest' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'updateComputerService' : ActorMethod<
    [bigint, ComputerServiceInput],
    undefined
  >,
  'updateProduct' : ActorMethod<[bigint, ProductUpdateInput], undefined>,
  'updateServiceRequestStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];