/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AgricultureTipInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'crop' : IDL.Text,
});
export const ComputerServiceInput = IDL.Record({
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const Department = IDL.Variant({
  'computer' : IDL.Null,
  'agriculture' : IDL.Null,
});
export const ProductUpdateInput = IDL.Record({
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'department' : Department,
  'price' : IDL.Float64,
});
export const AgricultureTip = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'crop' : IDL.Text,
});
export const ComputerService = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'department' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'department' : Department,
  'price' : IDL.Float64,
});
export const ServiceRequest = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'serviceType' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAgricultureTip' : IDL.Func([AgricultureTipInput], [IDL.Nat], []),
  'addComputerService' : IDL.Func([ComputerServiceInput], [IDL.Nat], []),
  'addProduct' : IDL.Func([ProductUpdateInput], [IDL.Nat], []),
  'deleteAgricultureTip' : IDL.Func([IDL.Nat], [], []),
  'deleteComputerService' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllAgricultureTips' : IDL.Func([], [IDL.Vec(AgricultureTip)], ['query']),
  'getAllComputerServices' : IDL.Func(
      [],
      [IDL.Vec(ComputerService)],
      ['query'],
    ),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getEnquiriesByDepartment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Enquiry)],
      ['query'],
    ),
  'getProductsByDepartment' : IDL.Func(
      [Department],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitServiceRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateComputerService' : IDL.Func([IDL.Nat, ComputerServiceInput], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, ProductUpdateInput], [], []),
  'updateServiceRequestStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AgricultureTipInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'crop' : IDL.Text,
  });
  const ComputerServiceInput = IDL.Record({
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Department = IDL.Variant({
    'computer' : IDL.Null,
    'agriculture' : IDL.Null,
  });
  const ProductUpdateInput = IDL.Record({
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'department' : Department,
    'price' : IDL.Float64,
  });
  const AgricultureTip = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'crop' : IDL.Text,
  });
  const ComputerService = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Enquiry = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'department' : Department,
    'price' : IDL.Float64,
  });
  const ServiceRequest = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'serviceType' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addAgricultureTip' : IDL.Func([AgricultureTipInput], [IDL.Nat], []),
    'addComputerService' : IDL.Func([ComputerServiceInput], [IDL.Nat], []),
    'addProduct' : IDL.Func([ProductUpdateInput], [IDL.Nat], []),
    'deleteAgricultureTip' : IDL.Func([IDL.Nat], [], []),
    'deleteComputerService' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllAgricultureTips' : IDL.Func(
        [],
        [IDL.Vec(AgricultureTip)],
        ['query'],
      ),
    'getAllComputerServices' : IDL.Func(
        [],
        [IDL.Vec(ComputerService)],
        ['query'],
      ),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getEnquiriesByDepartment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Enquiry)],
        ['query'],
      ),
    'getProductsByDepartment' : IDL.Func(
        [Department],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitServiceRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateComputerService' : IDL.Func([IDL.Nat, ComputerServiceInput], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, ProductUpdateInput], [], []),
    'updateServiceRequestStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };