/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ServiceRequest {
    id: bigint;
    customerName: string;
    status: string;
    serviceType: string;
    description: string;
    timestamp: bigint;
    phone: string;
}
export interface AgricultureTipInput {
    title: string;
    content: string;
    crop: string;
}
export interface AgricultureTip {
    id: bigint;
    title: string;
    content: string;
    crop: string;
}
export interface ProductUpdateInput {
    inStock: boolean;
    name: string;
    description: string;
    category: string;
    department: Department;
    price: number;
}
export interface ComputerService {
    id: bigint;
    duration: string;
    name: string;
    description: string;
    price: number;
}
export interface Enquiry {
    id: bigint;
    customerName: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
    department: string;
}
export interface ComputerServiceInput {
    duration: string;
    name: string;
    description: string;
    price: number;
}
export interface Product {
    id: bigint;
    inStock: boolean;
    name: string;
    description: string;
    category: string;
    department: Department;
    price: number;
}
export enum Department {
    computer = "computer",
    agriculture = "agriculture"
}
export interface backendInterface {
    addAgricultureTip(tipData: AgricultureTipInput): Promise<bigint>;
    addComputerService(serviceData: ComputerServiceInput): Promise<bigint>;
    addProduct(productData: ProductUpdateInput): Promise<bigint>;
    deleteAgricultureTip(id: bigint): Promise<void>;
    deleteComputerService(id: bigint): Promise<void>;
    deleteProduct(id: bigint): Promise<void>;
    getAllAgricultureTips(): Promise<Array<AgricultureTip>>;
    getAllComputerServices(): Promise<Array<ComputerService>>;
    getAllEnquiries(): Promise<Array<Enquiry>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllServiceRequests(): Promise<Array<ServiceRequest>>;
    getEnquiriesByDepartment(department: string): Promise<Array<Enquiry>>;
    getProductsByDepartment(department: Department): Promise<Array<Product>>;
    submitEnquiry(customerName: string, phone: string, email: string, message: string, department: string): Promise<bigint>;
    submitServiceRequest(customerName: string, phone: string, serviceType: string, description: string): Promise<bigint>;
    updateComputerService(id: bigint, serviceData: ComputerServiceInput): Promise<void>;
    updateProduct(id: bigint, productData: ProductUpdateInput): Promise<void>;
    updateServiceRequestStatus(id: bigint, status: string): Promise<void>;
}
import type { Department as _Department, Product as _Product, ProductUpdateInput as _ProductUpdateInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAgricultureTip(arg0: AgricultureTipInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAgricultureTip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAgricultureTip(arg0);
            return result;
        }
    }
    async addComputerService(arg0: ComputerServiceInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComputerService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComputerService(arg0);
            return result;
        }
    }
    async addProduct(arg0: ProductUpdateInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_ProductUpdateInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_ProductUpdateInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAgricultureTip(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAgricultureTip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAgricultureTip(arg0);
            return result;
        }
    }
    async deleteComputerService(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComputerService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComputerService(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllAgricultureTips(): Promise<Array<AgricultureTip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAgricultureTips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAgricultureTips();
            return result;
        }
    }
    async getAllComputerServices(): Promise<Array<ComputerService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComputerServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComputerServices();
            return result;
        }
    }
    async getAllEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnquiries();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServiceRequests(): Promise<Array<ServiceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServiceRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServiceRequests();
            return result;
        }
    }
    async getEnquiriesByDepartment(arg0: string): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnquiriesByDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnquiriesByDepartment(arg0);
            return result;
        }
    }
    async getProductsByDepartment(arg0: Department): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByDepartment(to_candid_Department_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByDepartment(to_candid_Department_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitEnquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnquiry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnquiry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitServiceRequest(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitServiceRequest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitServiceRequest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateComputerService(arg0: bigint, arg1: ComputerServiceInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComputerService(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComputerService(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: ProductUpdateInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_ProductUpdateInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_ProductUpdateInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateServiceRequestStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceRequestStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceRequestStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Department_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Department): Department {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    inStock: boolean;
    name: string;
    description: string;
    category: string;
    department: _Department;
    price: number;
}): {
    id: bigint;
    inStock: boolean;
    name: string;
    description: string;
    category: string;
    department: Department;
    price: number;
} {
    return {
        id: value.id,
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        category: value.category,
        department: from_candid_Department_n8(_uploadFile, _downloadFile, value.department),
        price: value.price
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    computer: null;
} | {
    agriculture: null;
}): Department {
    return "computer" in value ? Department.computer : "agriculture" in value ? Department.agriculture : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Department_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): _Department {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ProductUpdateInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductUpdateInput): _ProductUpdateInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inStock: boolean;
    name: string;
    description: string;
    category: string;
    department: Department;
    price: number;
}): {
    inStock: boolean;
    name: string;
    description: string;
    category: string;
    department: _Department;
    price: number;
} {
    return {
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        category: value.category,
        department: to_candid_Department_n3(_uploadFile, _downloadFile, value.department),
        price: value.price
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): {
    computer: null;
} | {
    agriculture: null;
} {
    return value == Department.computer ? {
        computer: null
    } : value == Department.agriculture ? {
        agriculture: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
